config/routes.rb
Flatbuddy::Application.routes.draw do
  resource :flats

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users

  resource :profiles

  resources :sessions

  resources :tags

  resources :flatmates

  resources :tasks
  root 'static#index'

  

end

app/models/flat.rb
class Flat < ActiveRecord::Base
    has_many :flatmates
    has_many :tasks
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_filter :authorize, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  
  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)
    @flat.flatmates << current_user.flatmate

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flat }
      else
        format.html { render action: 'new' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:name)
    end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
  <% if @flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
      <% @flat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render 'form' %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<h1>Listing flats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.name %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flat', new_flat_path %>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flat.name %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>