config/routes.rb
Flatbuddy::Application.routes.draw do
  resource :flats

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users

  resource :profiles

  resources :sessions

  resources :tags

  resources :flatmates

  resources :tasks
  root 'static#index'

  

end

app/models/flatmate.rb
class Flatmate < ActiveRecord::Base
    has_many :tasks
    belongs_to :user
    belongs_to :flat


end

app/controllers/flatmates_controller.rb
class FlatmatesController < ApplicationController
  before_action :set_flatmate, only: [:show, :edit, :update, :destroy]

  # GET /flatmates
  # GET /flatmates.json
  def index
    @flatmates = Flatmate.all
  end

  # GET /flatmates/1
  # GET /flatmates/1.json
  def show
  end

  # GET /flatmates/new
  def new
    @flatmate = Flatmate.new
  end

  # GET /flatmates/1/edit
  def edit
  end

  # POST /flatmates
  # POST /flatmates.json
  def create
    @flatmate = Flatmate.new(flatmate_params)

    respond_to do |format|
      if @flatmate.save
        format.html { redirect_to @flatmate, notice: 'Flatmate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flatmate }
      else
        format.html { render action: 'new' }
        format.json { render json: @flatmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flatmates/1
  # PATCH/PUT /flatmates/1.json
  def update
    respond_to do |format|
      if @flatmate.update(flatmate_params)
        format.html { redirect_to @flatmate, notice: 'Flatmate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flatmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flatmates/1
  # DELETE /flatmates/1.json
  def destroy
    @flatmate.destroy
    respond_to do |format|
      format.html { redirect_to flatmates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flatmate
      @flatmate = Flatmate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flatmate_params
      params.require(:flatmate).permit(:name)
    end
end

app/helpers/flatmates_helper.rb
module FlatmatesHelper
end

app/views/flatmates/_form.html.erb
<%= form_for(@flatmate) do |f| %>
  <% if @flatmate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flatmate.errors.count, "error") %> prohibited this flatmate from being saved:</h2>

      <ul>
      <% @flatmate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flatmates/edit.html.erb
<h1>Editing flatmate</h1>

<%= render 'form' %>

<%= link_to 'Show', @flatmate %> |
<%= link_to 'Back', flatmates_path %>

app/views/flatmates/index.html.erb
<h1>Listing flatmates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flatmates.each do |flatmate| %>
      <tr>
        <td><%= flatmate.name %></td>
        <td><%= link_to 'Show', flatmate %></td>
        <td><%= link_to 'Edit', edit_flatmate_path(flatmate) %></td>
        <td><%= link_to 'Destroy', flatmate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flatmate', new_flatmate_path %>

app/views/flatmates/new.html.erb
<h1>New flatmate</h1>

<%= render 'form' %>

<%= link_to 'Back', flatmates_path %>

app/views/flatmates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flatmate.name %>
</p>

<%= link_to 'Edit', edit_flatmate_path(@flatmate) %> |
<%= link_to 'Back', flatmates_path %>