config/routes.rb
Flatbuddy::Application.routes.draw do
  resource :flats

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users

  resource :profiles

  resources :sessions

  resources :tags

  resources :flatmates

  resources :tasks
  root 'static#index'

  

end

app/models/flat.rb
class Flat < ActiveRecord::Base
    has_many :flatmates
    has_many :tasks
end

app/models/flatmate.rb
class Flatmate < ActiveRecord::Base
    has_many :tasks
    belongs_to :user
    belongs_to :flat


end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :task_tags
    has_many :tasks, :through => :task_tags
end

app/models/task.rb
class Task < ActiveRecord::Base
    has_many :task_tags
    has_many :tags, :through => :task_tags
    belongs_to :flatmate
    belongs_to :flat 

    def overdue?
        due_date < Date.today && !completed?
    end

    def flatmate_name
        if flatmate
          flatmate.name 
        else
          ""
        end
    end


end

app/models/task_tag.rb
class TaskTag < ActiveRecord::Base
    belongs_to :task 
    belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates_uniqueness_of :email
    has_one :flatmate
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_filter :authorize, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  
  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)
    @flat.flatmates << current_user.flatmate

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flat }
      else
        format.html { render action: 'new' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:name)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
   before_filter :authorize

   def show
      @user = current_user

    end


    def edit
      @user = current_user

    end

    def update
      @user = current_user
      respond_to do |format|
        if @user.update(profile_params)
          format.html { redirect_to root_url, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

     private
    
    def profile_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index       
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authorize, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @tasks = current_user.flatmate.flat.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.flat = current_user.flatmate.flat

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :due_date, :description, :flatmate_id, :completed, :tag_ids => [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   
    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url, notice: "Welcome to Flatbuddy, thank you for signing up!"
      else
        render "new"
      end
    end

  

    private
    
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flatmates_helper.rb
module FlatmatesHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flatbuddy</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="http://fonts.googleapis.com/css?family=Corben:bold" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Nobile" rel="stylesheet" type="text/css">
</head>
<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand flatbuddy" href="/" ><i class="icon-home icon-white"></i> Flatbuddy</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Browse Tasks", tasks_path if current_user && current_user.flatmate.present? %></li>
            <li><%= link_to 'New Task', new_task_path if current_user && current_user.flatmate.present? %></li>
            <li><%= link_to 'New Flat', new_flats_path if current_user && current_user.flatmate.nil? %></li>

          </ul>
          
          <div class="btn pull-right">
              <% if current_user %>
                Logged in as <%= link_to current_user.name || current_user.email, edit_profiles_path %>.
                <%= link_to "Log Out", logout_path %>
              <% else %>
                <i class="icon-user" style="color: #E01B56;"></i>
                <%= link_to "Log In", login_path %>
              <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="wrapper">

   <div class="container">
  
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
  
        <%= yield %>
  
   </div>
  </div>
</body>

<footer class="navbar navbar-fixed-bottom">
      <div class="container">
        <div class="row">
        <div class="span9" style ="text-align: left; font-family: 'corben';"> Flatbuddy </div>
        <div class="span3" style ="text-align: right;"> <i class="icon-heart icon-white"></i> Stay friends!</div>
       </div>
</footer>
</html>